name: Needs Demo Pipeline

on: [push]

jobs:
  # First job: build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Building the project..."

  # Second job: test, depends on build
  test:
    needs: build            # Runs *after* build completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests..."

  # Third job: lint, runs in parallel with test (no needs)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: echo "Linting code..."

  # Fourth job: deploy, depends on test and lint
  deploy:
    needs: [test, lint]     # Waits for both test and lint jobs to finish successfully
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Deploying app..."

  # Fifth job: notify, runs regardless of previous job outcomes
  notify:
    needs: deploy
    if: always()            # Runs even if deploy failed
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: echo "Sending notification email (success or failure)."
