name: CI Pipeline

on: [push]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Hello 1"

  job2:
    needs: echo-job  # This ensures job2 waits for echo-job to finish
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Hello 2"
