name: CI Pipeline

on: [push]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Hello 1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo " Hello 2"
